
#Kasper
name: Amin Abu-Taleb
description: Building some stuffs
meta_description: "The home page of Amin Abu-Taleb, software engineer @ Wise, former co-founder at Nextub."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
domain_name: "http://abutaleb.me"
google_analytics: "UA-69943574-1"

# Details for the RSS feed generator
url: "https://abutaleb.me"
author: "Amin Abu-Taleb"
bio: "Engineering Lead @ Wise. <br> Author https://abutaleb.me"
thumbnail_path: "profile.png"
image_path: "/assets/images"

# Disqus config
disqus-shortname: "Amin"
# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

# Internal nav
nav:
  main:
    writing: "/writing"
    projects: "/projects"

contact_urls:
  twitter:
    url: "https://twitter.com/AminAbuTaleb"
    label: "Twitter"
    icon: "twitter-square"
    username: "@AminAbuTaleb"
  linkedin:
    url: "https://www.linkedin.com/in/aminabutaleb"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/aabutaleb/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:amin@abutaleb.me"
    label: "Email"
    value: "amin@abutaleb.me"
    icon: "envelope-square"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
